name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
    - name: Install Dependencies
      run: |
        npm install -g yarn
        sudo apt install build-essential
    - name: Frontend
      run: |
        cd jms-frontend
        yarn install
        yarn build
        cd ..
    - name: Install Dependencies
      run: sudo apt install pkg-config libssl-dev libncurses-dev libdbus-1-dev isc-dhcp-server
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose

