name: CI

on: [push, pull_request]

jobs:
  build:
    name: "Build on ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/setup-node@v4
      with:
        node-version: '18.16.1'
    - name: Install Dependencies
      run: |
        npm install -g yarn
        sudo apt install build-essential pkg-config libssl-dev libncurses-dev libdbus-1-dev isc-dhcp-server
    - name: Frontend
      run: |
        cd jms-ui
        yarn install
        yarn build
        cd ..
    - name: Build
      run: cargo build
